### ISSUE TITLE
TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'

### ISSUE THREAD

**Issue by AJamesPhillips** [brianzinn/create-react-app-typescript-babylonjs#9]
I ran the following commands:

```
git clone git clone git@github.com:brianzinn/create-react-app-typescript-babylonjs.git
cd create-react-app-typescript-babylonjs
pnpm install
npm start
```

I got the following output & error:

```
> create-react-app-typescript-babylonjs@0.1.0 start
> react-scripts start

/Users/[...]/demo/node_modules/.pnpm/react-scripts@4.0.0_typescript@4.7.3/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/Users/[...]/demo/node_modules/.pnpm/react-scripts@4.0.0_typescript@4.7.3/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/Users/[...]/demo/node_modules/.pnpm/react-scripts@4.0.0_typescript@4.7.3/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by AJamesPhillips** [comment]
pnpm-lock.yaml file is:
[pnpm-lock.yaml.zip](https://github.com/brianzinn/create-react-app-typescript-babylonjs/files/8845115/pnpm-lock.yaml.zip)

**Comment by brianzinn** [comment]
i think just need to update typescript and ts-node.  i've been getting errors on many different projects lately.  thanks for reporting - I need to update this project React version and make sure some other reported issues are fixed downstream as well! 😄

**Comment by brianzinn** [comment]
closing from inactivity.  i dropped a react 18 update with latest CRA.  please re-open if you have any issues.  cheers.
